### ISSUE TITLE
[Tweets] Errors

### ISSUE THREAD

**Issue by Menteroth** [TrustyJAID/Trusty-cogs#113]
I posted this on Discord, but might as well do an issue here too.

```
Exception in thread Thread-161:
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 583, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(361 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\six.py", line 703, in reraise
    raise value
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(361 bytes read)', IncompleteRead(361 bytes read))
Exception in thread Thread-162:
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 583, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(348 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\six.py", line 703, in reraise
    raise value
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(348 bytes read)', IncompleteRead(348 bytes read))
C:\__\coding\Soundwave\cogs\Downloader\lib\feedparser\util.py:83: DeprecationWarning: To avoid breaking existing software while fixing issue 310, a te
mporary mapping has been created from `updated` to `published` if `updated` doesn't exist. This fallback will be removed in a future version of feedpa
rser.
  warnings.warn(
C:\__\coding\Soundwave\cogs\Downloader\lib\feedparser\util.py:98: DeprecationWarning: To avoid breaking existing software while fixing issue 310, a te
mporary mapping has been created from `updated_parsed` to `published_parsed` if `updated_parsed` doesn't exist. This fallback will be removed in a fut
ure version of feedparser.
  warnings.warn(
Exception in thread Thread-187:
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 583, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(72 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\six.py", line 703, in reraise
    raise value
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(72 bytes read)', IncompleteRead(72 bytes read))
```

**Comment by Menteroth** [comment]
I'm still getting this error. This is the most recent from a few minutes ago.
```
Exception in thread Thread-178:
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 518, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 583, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 553, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 437, in _error_catcher
    yield
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(228 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\six.py", line 703, in reraise
    raise value
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 289, in _run
    self._read_loop(resp)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 339, in _read_loop
    line = buf.read_line()
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\tweepy\streaming.py", line 200, in read_line
    self._buffer += self._stream.read(self._chunk_size)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\*\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\__\coding\Soundwave\cogs\Downloader\lib\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(228 bytes read)', IncompleteRead(228 bytes read))
```

**Comment by TrustyJAID** [comment]
This is not something that I can fix. The cog temporarily lost connection with twitter either their end or your end I'm not sure.
