### ISSUE TITLE
[Conversions] Incorrectly loading after restart

### ISSUE THREAD

**Issue by fixator10** [TrustyJAID/Trusty-cogs#114]
So, after bot's restart cog is loading incorrectly

1. Install Cog
2. Load it
3. Restart bot
4. Check loaded cogs - conversions is not loaded
5. Attempt to load it manually
6. Get `RuntimeError: There is already a cog named Conversions loaded.`
7. Attempt to load it again
8. Cog loaded

```py
[2020-03-22 09:13:04] [ERROR] red: Failed to load package conversions (timeout)
Traceback (most recent call last):
  File "/home/fixator/Red-V3/lib/python3.8/site-packages/redbot/core/bot.py", line 621, in pre_flight
    await asyncio.wait_for(self.load_extension(spec), 30)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by fixator10** [comment]
Seem to be fixed in https://github.com/TrustyJAID/Trusty-cogs/commit/257e6ff88b7fe5e309c7d7f9ef2428efe9524e24
