### ISSUE TITLE
[ReTrigger] Command Bug | retrigger explain

### ISSUE THREAD

**Issue by Menteroth** [TrustyJAID/Trusty-cogs#199]
```py
Exception in command 'retrigger explain'
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\retrigger\retrigger.py", line 1073, in explain
    data = infile.read()
  File "C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 11050: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "c:\__\coding\redenv\lib\site-packages\redbot\core\commands\commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 1307, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnicodeDecodeError: 
'charmap' codec can't decode byte 0x8f in position 11050: character maps to <undefined>
```

**Comment by TrustyJAID** [comment]
This has already been fixed, update the cog.

**Comment by Menteroth** [comment]
Sorry didn't know. Got no response.

**Comment by TrustyJAID** [comment]
my webhooks broke and didn't update in my channel when I updated, sorry.

**Comment by Menteroth** [comment]
No need to apologize. All good.
