### ISSUE TITLE
[EventPoster] Error in 'eventping'.

### ISSUE THREAD

**Issue by madebylydia** [TrustyJAID/Trusty-cogs#238]
**Describe the bug**
The command 'eventping' didn't accomplish.

**To Reproduce**
1. Create an event
2. Wait for some peoples to join (We were 8 persons)
3. Use `[p]eventping`

**Expected behavior**
The command get executed correctly.

**Traceback**
```py
Exception in command 'eventping'
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/bots/Miku/cogs/CogManager/cogs/eventposter/eventposter.py", line 285, in event_ping
    msg = event.mention(include_maybe) + ":\n" + message
TypeError: can only concatenate str (not "NoneType") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: can only concatenate str (not "NoneType") to str
```

**Additional context**
Contact me on Discord for more informations.

**Comment by madebylydia** [comment]
Apparently the command has already been used 1 time before this error happens, the first execution was fine without error. Keeping this open as it may be useful.
