### ISSUE TITLE
[extendedmodlog] Member join log not working :(

### ISSUE THREAD

**Issue by high-me** [TrustyJAID/Trusty-cogs#297]
Ignoring exception in on_member_join
Traceback (most recent call last):
File "/data/venv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
await coro(*args, **kwargs)
File "/data/cogs/CogManager/cogs/extendedmodlog/eventmixin.py", line 595, in on_member_join
possible_link = await self.get_invite_link(member)
File "/data/cogs/CogManager/cogs/extendedmodlog/eventmixin.py", line 513, in get_invite_link
possible_link = str(await guild.vanity_invite())
File "/data/venv/lib/python3.9/site-packages/discord/invite.py", line 357, in __str__
return self.url
File "/data/venv/lib/python3.9/site-packages/discord/invite.py", line 375, in url
return self.BASE + '/' + self.code
TypeError: can only concatenate str (not "NoneType") to str

**Comment by TrustyJAID** [comment]
This is happening because the guild in question is allowed to have a vanity URL but does not have one set. The actual error is happening in discord.py which has since been fixed on later releases in which Red is still working to upgrade to.
