### ISSUE TITLE
[ExtendedModLog][dpy2] Bulk deletes in thread are not logged

### ISSUE THREAD

**Issue by Injabie3** [TrustyJAID/Trusty-cogs#299]
**Describe the bug**
On bulk deletes in threads, nothing is logged in the configured modlog channel.

**To Reproduce**
Assuming a modlog channel has been created before with all events configured to log to said channel:
1. Create a thread.
2. Send some messages.
3. Enable the `cleanup` cog.
4. Run `[p]cleanup messages 4` or something similar.
5. Observe that messages are cleaned up in the thread.
6. Observe that nothing is logged in the modlog channel.
7. Observe that the following error is seen in the console:
```
[2023-01-07 16:06:48] [ERROR] discord.client: Ignoring exception in on_raw_bulk_message_delete
Traceback (most recent call last):
  File "/home/ubuntu/github/renchan/lib/python3.8/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/github/v3-data/cogs/CogManager/cogs/extendedmodlog/eventmixin.py", line 444, in on_raw_bulk_message_delete
    if await self.is_ignored_channel(guild, message_channel):
  File "/home/ubuntu/github/v3-data/cogs/CogManager/cogs/extendedmodlog/eventmixin.py", line 131, in is_ignored_channel
    if channel.id in ignored_channels:
AttributeError: 'NoneType' object has no attribute 'id'
```

**Expected behavior**
Bulk deletes are logged.

**Screenshots**
N/A

**Additional context**
Running on:
- Red 3.5.0.dev1
- discord.py 2.1.0

**Comment by Injabie3** [comment]
Thanks!
