### ISSUE TITLE
[Citation] Error on [p]citate

### ISSUE THREAD

**Issue by Twentysix26** [TrustyJAID/Trusty-cogs#322]
**Describe the bug**
An exception is raised when I try to make a citation

**To Reproduce**
1. Install the cog (1.2.0)
2. Issue `[p]citate test`

**Expected behavior**
I expected a citation to be sent in the chat

**Screenshots**
.

**Additional context**
```py
Exception in command 'citate'
Traceback (most recent call last):
  File "/***/lib/python3.9/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/***-data/cogs/CogManager/cogs/citation/citation.py", line 127, in citate
    file = await self.make_citation(
  File "/***-data/cogs/CogManager/cogs/citation/citation.py", line 317, in make_citation
    temp: BytesIO = await asyncio.wait_for(task, timeout=60)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/***-data/cogs/CogManager/cogs/citation/citation.py", line 336, in make_citation_gif
    base_img = factory.generate_image(content, penalty, title, barcode)
  File "/***-data/cogs/CogManager/cogs/citation/citations/factory.py", line 113, in generate_image
    self._generate(draw, height, lines, penalty, title, barcode)
  File "/***-data/cogs/CogManager/cogs/citation/citations/factory.py", line 140, in _generate
    barcode_width = self._print_barcode(draw, barcode)
  File "/***-data/cogs/CogManager/cogs/citation/citations/factory.py", line 418, in _print_barcode
    self._rect(draw, end - offset - x, 3, x, 6, color)
  File "/***-data/cogs/CogManager/cogs/citation/citations/factory.py", line 307, in _rect
    draw.rectangle((x * m, y * m, (x + w) * m - 1, (y + h) * m - 1), color)
  File "/***-data/cogs/Downloader/lib/PIL/ImageDraw.py", line 292, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: x1 must be greater than or equal to x0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/***/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/***/lib/python3.9/site-packages/redbot/core/commands/commands.py", line 783, in invoke
    await super().invoke(ctx)
  File "/***/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1647, in invoke
    await super().invoke(ctx)
  File "/***/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/***/lib/python3.9/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: x1 must be greater than or equal to x0
```

**Comment by TrustyJAID** [comment]
resolved in https://github.com/TrustyJAID/Trusty-cogs/commit/7276f13a15120978787cc01c6b99e9a048e6e042 .
