### ISSUE TITLE
[Citation] Error in command 'citate'

### ISSUE THREAD

**Issue by CamoMano** [TrustyJAID/Trusty-cogs#344]
**Describe the bug**
Running the command gives an exception

**To Reproduce**
1. Install the latest version of the cog
2. Run citate test

**Expected behavior**
It should make a citation

**Additional context**
```python

Exception in command 'citate'
Traceback (most recent call last):
  File "/home/debian/redenv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/debian/bots/handy/cogs/CogManager/cogs/citation/citation.py", line 223, in citate
    file = await self.make_citation(
  File "/home/debian/bots/handy/cogs/CogManager/cogs/citation/citation.py", line 458, in make_citation
    temp: BytesIO = await asyncio.wait_for(task, timeout=60)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 447, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/debian/bots/handy/cogs/CogManager/cogs/citation/citation.py", line 492, in make_citation_gif
    new_image.save(
  File "/home/debian/bots/handy/cogs/Downloader/lib/PIL/Image.py", line 2605, in save
    save_handler(self, fp, filename)
  File "/home/debian/bots/handy/cogs/Downloader/lib/PIL/GifImagePlugin.py", line 774, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/home/debian/bots/handy/cogs/Downloader/lib/PIL/GifImagePlugin.py", line 787, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "/home/debian/bots/handy/cogs/Downloader/lib/PIL/GifImagePlugin.py", line 700, in _write_multiple_frames
    background_im.putpalette(im_frames[0].im.palette)
  File "/home/debian/bots/handy/cogs/Downloader/lib/PIL/Image.py", line 2103, in putpalette
    self.load()  # install new palette
  File "/home/debian/bots/handy/cogs/Downloader/lib/PIL/Image.py", line 909, in load
    self.im.putpalette(self.palette.mode, mode, arr)
ValueError: invalid palette size

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/debian/redenv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/debian/redenv/lib/python3.10/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/debian/redenv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1655, in invoke
    await super().invoke(ctx)
  File "/home/debian/redenv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/debian/redenv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid palette size

```

**Comment by TrustyJAID** [comment]
Hi, thanks for the issue. This is actually an issue upstream with https://github.com/python-pillow/Pillow/issues/8493. It looks like they won't include a fix for the issue until the next release cycle scheduled for January 2, 2025. In the meantime you can downgrade your pillow install to a version prior to 11.0 and have the cog continue to function.

**Comment by ArcasCZ** [comment]
Just a friendly reminder that the Pillow was updated to 11.1.0 recently, which should address the issue.
