### ISSUE TITLE
[ReTrigger] cool down cannot find trigger name

### ISSUE THREAD

**Issue by designbyadrian** [TrustyJAID/Trusty-cogs#37]
Prerequisite:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/2064558/59592022-1b37d600-90e7-11e9-93e3-cbfaf869f887.png">

Trying command: `!retrigger cooldown geraldoresponse 60`

Bot responds with: `Error in command 'retrigger cooldown'. Check your console or logs for details.`

Server console log:

```
Jun 17 09:03:27 geraldo redbot[6991]: [17/06/2019 09:03] ERROR events on_command_error 202: Exception in command 'retrigger cooldown'
Jun 17 09:03:27 geraldo redbot[6991]: Traceback (most recent call last):
Jun 17 09:03:27 geraldo redbot[6991]:   File "/home/designbyadrian/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 79, in wr
Jun 17 09:03:27 geraldo redbot[6991]:     ret = await coro(*args, **kwargs)
Jun 17 09:03:27 geraldo redbot[6991]:   File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/retrigger/retrigger.py", line 1
Jun 17 09:03:27 geraldo redbot[6991]:     trigger_list[name] = trigger.to_json()
Jun 17 09:03:27 geraldo redbot[6991]: NameError: name 'name' is not defined
```

**Comment by TrustyJAID** [comment]
Update your cogs, this was fixed already.
