### ISSUE TITLE
CrabRave Issue

### ISSUE THREAD

**Issue by cyberofficial** [TrustyJAID/Trusty-cogs#63]
I get this error

```py
[2019-08-30 07:28:57] [ERROR] red: Exception in command 'crab'
Traceback (most recent call last):
  File "/home/joe/SkyNet30/cogs/Downloader/lib/moviepy/video/VideoClip.py", line 1161, in __init__
    subprocess_call(cmd, logger=None)
  File "/home/joe/SkyNet30/cogs/Downloader/lib/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert: delegate library support not built-in '/home/joe/SkyNet30/cogs/CrabRave/Verdana.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1810.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: no images defined `PNG32:/tmp/tmps1z2q22j.png' @ error/convert.c/ConvertImageCommand/3273.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/joe/SkyNet30/cogs/CogManager/cogs/crabrave/crabrave.py", line 82, in crab
    await asyncio.wait_for(task, timeout=300)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/joe/SkyNet30/cogs/CogManager/cogs/crabrave/crabrave.py", line 106, in make_crab
    text = TextClip(t[0], fontsize=48, color="white", font=fp)
  File "/home/joe/SkyNet30/cogs/Downloader/lib/moviepy/video/VideoClip.py", line 1170, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: delegate library support not built-in '/home/joe/SkyNet30/cogs/CrabRave/Verdana.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1810.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: no images defined `PNG32:/tmp/tmps1z2q22j.png' @ error/convert.c/ConvertImageCommand/3273.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```

Don't know what to do fir this

**Comment by TrustyJAID** [comment]
See the install guide for NotSoBot cog [here](https://github.com/TrustyJAID/Trusty-cogs/tree/master/notsobot). You'll have to install ImageMagick from source for this to work.

**Comment by cyberofficial** [comment]
Issue was resolved!
Thank you.
