### ISSUE TITLE
[ELEMENTS] Mendeleev

### ISSUE THREAD

**Issue by Menteroth** [TrustyJAID/Trusty-cogs#84]
Trying to install with `pipinstall mendeleev`.
```dos
    ERROR: Command errored out with exit status 1:
     command: 'c:\__\coding\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\*\\AppData\\Local\\Temp\\
pip-install-17i46ch7\\mendeleev\\setup.py'"'"'; __file__='"'"'C:\\Users\\*\\AppData\\Local\\Temp\\pip-install-17i46ch7\\mendeleev\\setup.py'"'"';f
=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exe
c'"'"'))' egg_info --egg-base 'C:\Users\*\AppData\Local\Temp\pip-install-17i46ch7\mendeleev\pip-egg-info'
         cwd: C:\Users\*\AppData\Local\Temp\pip-install-17i46ch7\mendeleev\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\*\AppData\Local\Temp\pip-install-17i46ch7\mendeleev\setup.py", line 68, in <module>
        setup_package()
      File "C:\Users\*\AppData\Local\Temp\pip-install-17i46ch7\mendeleev\setup.py", line 56, in setup_package
        long_description=readme(),
      File "C:\Users\*\AppData\Local\Temp\pip-install-17i46ch7\mendeleev\setup.py", line 40, in readme
        return freadme.read()
      File "C:\Users\*\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 14373: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[2019-12-15 09:40:16] [ERROR] red.downloader: Something went wrong when installing the following requirements: mendeleev
```

**Comment by TrustyJAID** [comment]
This is an issue with the [mendeleev repo](https://github.com/lmmentel/mendeleev) upstream when trying to install on windows. I would look there for answers on fixing a normal windows install.

**Comment by Menteroth** [comment]
Found the regular pip installation there, but doesn't work because of the problem.

This worked though. Installed in the venv.
```
pip install git+https://github.com/lmmentel/mendeleev.git
```
But I am not sure how to make use of it for the cog, because I tried to install `elements` again but I still get the same error as it's trying to install it.

**Comment by TrustyJAID** [comment]
Once the module is installed in your bots environment you can simply ensure the cog files are in the CogManager folder inside the bots install directory and then load the cog.

**Comment by Menteroth** [comment]
I copied the elements folder from RepoManager into CogManager and that worked. 
Thanks for the help.
