### ISSUE TITLE
[ExtendedModLog] Ignoring exception in on_member_update

### ISSUE THREAD

**Issue by JamsRepos** [TrustyJAID/Trusty-cogs#91]
```0|NexusBot  | Ignoring exception in on_member_update
0|NexusBot  | Traceback (most recent call last):
0|NexusBot  |   File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 270, in _run_event
0|NexusBot  |     await coro(*args, **kwargs)
0|NexusBot  |   File "/home/nexusnation/NexusBot/cogs/CogManager/cogs/extendedmodlog/eventmixin.py", line 1314, in on_member_update
0|NexusBot  |     channel = await self.modlog_channel(guild, "user_change")
0|NexusBot  |   File "/home/nexusnation/NexusBot/cogs/CogManager/cogs/extendedmodlog/eventmixin.py", line 96, in modlog_channel
0|NexusBot  |     if settings["channel"]:
0|NexusBot  | KeyError: 'channel'

**Comment by TrustyJAID** [comment]
Fixed in [5ea1e07.](https://github.com/TrustyJAID/Trusty-cogs/commit/5ea1e07830c367ecdd107edd6e08bc97f999b618)
